version: "3.8"

services:
  server:
    build: ./server
    container_name: server
    ports:
      - "4444:3000"          # host:container
    volumes:
      - ./server:/app        # исходники
      - /app/node_modules    # чтобы локальные node_modules не перекрыли контейнерные
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Windows + WSL/FUSE
      - CHOKIDAR_INTERVAL=300

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
    stdin_open: true   # чтобы работали prompts/React-refresh
    tty: true
